name: K8S YAML Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install DaTree
        run: curl https://get.datree.io | /bin/bash

      - name: Scan with DaTree
        run: datree test ./kubernetes/*.yml
        env:
          DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 
